<?php
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;
use Faker\Factory as Faker;
use App\palabra;


class spalabras extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $palabra = array(
            0 => 'Abanico',
            1 => 'Avion',
            2 => 'Barco',
            3 => 'Balon',
            4 => 'Caballo',
            5 => 'Cereza',
            6 => 'Dados',
            7 => 'Doctor',
            8 => 'Espejo',
            9 => 'Embudo',
            10 => 'Fosforo',
            11 => 'Familia',
            12 => 'Guante',
            13 => 'Guitarra',
            14 => 'Hacha',
            15 => 'Hielo',
            16 => 'Isla',
            17 => 'Impresora',
            18 => 'Jarra',
            19 => 'Joya',
            20 => 'Kayac',
            21 => 'Kiwi',
            22 => 'Lampara',
            23 => 'Luna',
            24 => 'Mesa',
            25 => 'Mapa',
            26 => 'Nube',
            27 => 'Nuez',
            28 => 'Oreja',
            29 => 'Ola',
            30 => 'Peine',
            31 => 'Pila',
            32 => 'Queso',
            33 => 'Quirofano',
            34 => 'Rueda',
            35 => 'Rana',
            36 => 'Sombrilla',
            37 => 'Silla',
            38 => 'Taza',
            39 => 'Tambor',
            40 => 'Universo',
            41 => 'Urna',
            42 => 'Vela',
            43 => 'Ventilador',
            44 => 'Xilofono',
            45 => 'Xenon',
            46 => 'Yate',
            47 => 'Yogur',
            48 => 'Zapatos',
            49 => 'Zafiro'
        );
        $descripcion = array(
            0 => 'Abanico',
            1 => 'Avion',
            2 => 'Barco',
            3 => 'Balon',
            4 => 'Caballo',
            5 => 'Cereza',
            6 => 'Dados',
            7 => 'Doctor',
            8 => 'Espejo',
            9 => 'Embudo',
            10 => 'Fosforo',
            11 => 'Familia',
            12 => 'Guante',
            13 => 'Guitarra',
            14 => 'Hacha',
            15 => 'Hielo',
            16 => 'Isla',
            17 => 'Impresora',
            18 => 'Jarra',
            19 => 'Joya',
            20 => 'Kayac',
            21 => 'Kiwi',
            22 => 'Lampara',
            23 => 'Luna',
            24 => 'Mesa',
            25 => 'Mapa',
            26 => 'Nube',
            27 => 'Nuez',
            28 => 'Oreja',
            29 => 'Ola',
            30 => 'Peine',
            31 => 'Pila',
            32 => 'Queso',
            33 => 'Quirofano',
            34 => 'Rueda',
            35 => 'Rana',
            36 => 'Sombrilla',
            37 => 'Silla',
            38 => 'Taza',
            39 => 'Tambor',
            40 => 'Universo',
            41 => 'Urna',
            42 => 'Vela',
            43 => 'Ventilador',
            44 => 'Xilofono',
            45 => 'Xenon',
            46 => 'Yate',
            47 => 'Yogur',
            48 => 'Zapatos',
            49 => 'Zafiro'
        );
        $dificultad = array(
            0 => 'Facil',
            1 => 'Normal',
            2 => 'Facil',
            3 => 'Normal',
            4 => 'Facil',
            5 => 'Normal',
            6 => 'Facil',
            7 => 'Normal',
            8 => 'Facil',
            9 => 'Normal',
            10 => 'Facil',
            11 => 'Normal',
            12 => 'Facil',
            13 => 'Normal',
            14 => 'Facil',
            15 => 'Normal',
            16 => 'Facil',
            17 => 'Normal',
            18 => 'Facil',
            19 => 'Normal',
            20 => 'Facil',
            21 => 'Normal',
            22 => 'Facil',
            23 => 'Normal',
            24 => 'Facil',
            25 => 'Normal',
            26 => 'Facil',
            27 => 'Normal',
            28 => 'Facil',
            29 => 'Normal',
            30 => 'Facil',
            31 => 'Normal',
            32 => 'Facil',
            33 => 'Normal',
            34 => 'Facil',
            35 => 'Normal',
            36 => 'Facil',
            37 => 'Normal',
            38 => 'Facil',
            39 => 'Normal',
            40 => 'Facil',
            41 => 'Normal',
            42 => 'Facil',
            43 => 'Normal',
            44 => 'Facil',
            45 => 'Normal',
            46 => 'Facil',
            47 => 'Normal',
            48 => 'Facil',
            49 => 'Normal'
        );
        //letras
        //ABCDEFGHIJKLMNOPQRSTUVXYZ 
        $letra = array(
            0 => 'A',
            1 => 'A',
            2 => 'B',
            3 => 'B',
            4 => 'C',
            5 => 'C',
            6 => 'D',
            7 => 'D',
            8 => 'E',
            9 => 'E',
            10 => 'F',
            11 => 'F',
            12 => 'G',
            13 => 'G',
            14 => 'H',
            15 => 'H',
            16 => 'I',
            17 => 'I',
            18 => 'J',
            19 => 'J',
            20 => 'K',
            21 => 'K',
            22 => 'L',
            23 => 'L',
            24 => 'M',
            25 => 'M',
            26 => 'N',
            27 => 'N',
            28 => 'O',
            29 => 'O',
            30 => 'P',
            31 => 'P',
            32 => 'Q',
            33 => 'Q',
            34 => 'R',
            35 => 'R',
            36 => 'S',
            37 => 'S',
            38 => 'T',
            39 => 'T',
            40 => 'U',
            41 => 'U',
            42 => 'V',
            43 => 'V',
            44 => 'X',
            45 => 'X',
            46 => 'Y',
            47 => 'Y',
            48 => 'Z',
            49 => 'Z'
        );
        
        for ($i=0; $i<50; $i++){
            $palabras = $palabra[$i];
            $descripciones = $descripcion[$i];
            $dificultades = $dificultad[$i];
            $letras = $letra[$i];
            palabra::create([
                'Letra'      => $letras,
                'Palabra' 	 =>	$palabras,
                'Tipo'       => 'Empieza',
                'Descripcion'=> $descripciones,
                'Dificultad' =>	$dificultades,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ]);
        }
       
        
    }
}
